package lib;

public class VerificationToken {
	public static class NewUser{
		public static final String token ="eyJhbGciOiJSUzUxMiJ9.eyJzdWIiOiJhY2NvdW50X2FjdGl2YXRpb24iLCJlbWFpbCI6ImRnejY2MDM5QGRzaWF5LmNvbSIsImV4cCI6MTQ4MTI3MTU1OX0.ks4GS5X1lkZ8_nqtkUiczwKVB_gyWlOtekEMlkgiJN4iNRJcfoHis2BISjpY5OGeaap9DTaNYCOuIH0pDEM3G4-uiApLE8qAwMjylLdkzXWFR5zc4rI4xZTzDePWHjjBdEquQ6-hlUkofXQriQCybOdoHK6mbz-QHLwmlrECQMAKIu9vLHSnTU_Ed0KtnWdDiSs0fkAO6eXHM2hu5LnOjedgyId1cgXEiOZOyv19Gm4_EN3dIjrM9IClrywboKX3ssP0GoyllULPzK0zJfYxkmBrJjnpvT_lj3dSi9FUNYApFCzFiUC8_a_vRVmk83yrwkRRMQTAkZgcV2MTIuPJCg";
	}
	public static class AuthToken{
		public static final String token ="";
	}

}
